# Generated by Django 3.0.7 on 2020-07-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200504_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='age',
            field=models.IntegerField(),
        ),
    ]
